services:
  - type: web
    name: cardinal-otunga-app
    env: python
    plan: free
    # install OS libraries before Python packages (required for Pillow)
    buildCommand: apt-get update && apt-get install -y libjpeg-dev zlib1g-dev && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn school.wsgi
    envVars:
      - key: DEBUG
        value: "False"
      - key: USE_POSTGRES
        value: "True"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cardinal-otunga-db
          property: connectionString
  
  - type: pserv
    name: cardinal-otunga-db
    env: postgres
    plan: free
    ipAllowList: []
